# Use the official Node.js version 14.21.3 image as the base image
FROM node:14.21.3

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application files (excluding node_modules)
COPY . /app

# Install dependencies
RUN npm install

# Expose the port on which the app will run (change it according to your application's configuration)
EXPOSE 3000

# Start the React application
CMD ["npm", "start"]

